### ISSUE TITLE
I hope the author can solve a problem

### ISSUE THREAD

**Issue by FXDYJ** [uzair-ashraf/genshin-impact-wish-simulator#106]
Error content：It looks like this is your first time using Cypress: 6.0.1

  ✖  Verifying Cypress can run /root/.cache/Cypress/6.0.1/Cypress
    → Cypress Version: 6.0.1
Cypress failed to start.

This is usually caused by a missing library or dependency.

The error below should indicate which dependency is missing.

https://on.cypress.io/required-dependencies

If you are using Docker, we provide containers with all required dependencies installed.

----------

/root/.cache/Cypress/6.0.1/Cypress/Cypress: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

----------

Platform: linux (Ubuntu - 20.04)
Cypress Version: 6.0.1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genshin-impact-wish-simulator@2.1.1 cypress: `cypress run --headed`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the genshin-impact-wish-simulator@2.1.1 cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-01T12_55_36_469Z-debug.log
{ Error: Command failed with exit code 1: npm run cypress
    at makeError (/www/wwwroot/genshin-impact-wish-simulator/node_modules/start-server-and-test/node_modules/execa/lib/error.js:56:11)
    at handlePromise (/www/wwwroot/genshin-impact-wish-simulator/node_modules/start-server-and-test/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command: 'npm run cypress',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genshin-impact-wish-simulator@2.1.1 test:cypress: `start-server-and-test start http://localhost:3000 cypress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the genshin-impact-wish-simulator@2.1.1 test:cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-01T12_55_36_498Z-debug.log
ERROR: "test:cypress" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! genshin-impact-wish-simulator@2.1.1 test: `run-s test:*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the genshin-impact-wish-simulator@2.1.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-01T12_55_36_519Z-debug.log

**Comment by uzair-ashraf** [comment]
What operating system? and do you have chrome installed?
